import { describe, expect, test } from "bun:test";
import { buildPrompt } from "../prompt-builder";

describe("buildPrompt", () => {
  test("includes rich per-role details in the generated prompt", () => {
    const prompt = buildPrompt({
      title: "Acme",
      finalUrl: "https://acme.test",
      palette: [
        { role: "background", hex: "#f7f5ef" },
        { role: "accent", hex: "#0055ff" },
      ],
      fonts: {
        display: "Sora",
        body: "Inter",
        mono: "JetBrains Mono",
        headingSize: "56px",
        bodySize: "18px",
        lineHeight: "1.60",
      },
      tags: ["editorial", "airy"],
      layout: {
        structure: "Alternating hero and feature bands",
        width: "1280px",
        spacing: "Spacious",
        density: "Open",
        gap: "24px",
        sectionPadding: "96px",
      },
      sections: ["Hero", "Features", "Testimonials", "CTA"],
      radius: { label: "Rounded controls", average: 22 },
      shadow: "Soft edge lift",
      header: { label: "Centered wordmark + nav", height: "80px", navLinks: 5, hasCta: true },
      footer: { label: "Dense product footer", columns: "4 columns" },
      borders: { width: "Hairline (1px)", cardRadius: "28px", cardShadow: "Sparse shadow use" },
      buttonDetails: { height: "48px", style: "Solid fill" },
      description: "Premium workflow tooling for design teams.",
      componentStyles: {
        h1: {
          fontStack: "Sora, sans-serif",
          primaryFamily: "Sora",
          fontSizePx: 72,
          fontWeight: 800,
          lineHeightPx: 80,
          lineHeightRatio: 1.11,
          letterSpacingPx: -1.2,
          textTransform: "none",
          textDecoration: "none",
          color: "#111111",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: "h1",
          confidence: "high",
        },
        h2: {
          fontStack: "Sora, sans-serif",
          primaryFamily: "Sora",
          fontSizePx: 40,
          fontWeight: 700,
          lineHeightPx: 46,
          lineHeightRatio: 1.15,
          letterSpacingPx: -0.6,
          textTransform: "uppercase",
          textDecoration: "none",
          color: "#181818",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: "h2",
          confidence: "high",
        },
        h3: {
          fontStack: "Sora, sans-serif",
          primaryFamily: "Sora",
          fontSizePx: 28,
          fontWeight: 600,
          lineHeightPx: 34,
          lineHeightRatio: 1.2,
          letterSpacingPx: 0,
          textTransform: "none",
          textDecoration: "none",
          color: "#222222",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: "h3",
          confidence: "high",
        },
        body: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 18,
          fontWeight: 400,
          lineHeightPx: 31,
          lineHeightRatio: 1.72,
          letterSpacingPx: 0.2,
          textTransform: "none",
          textDecoration: "none",
          color: "#4a4a4a",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: "p",
          confidence: "high",
        },
        link: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 16,
          fontWeight: 500,
          lineHeightPx: 24,
          lineHeightRatio: 1.5,
          letterSpacingPx: 0,
          textTransform: "none",
          textDecoration: "underline",
          color: "#0055ff",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: "a",
          confidence: "high",
        },
        navLink: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 14,
          fontWeight: 600,
          lineHeightPx: 20,
          lineHeightRatio: 1.43,
          letterSpacingPx: 1.2,
          textTransform: "uppercase",
          textDecoration: "none",
          color: "#222222",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: "nav a",
          confidence: "high",
        },
        buttonPrimary: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 16,
          fontWeight: 600,
          lineHeightPx: 20,
          lineHeightRatio: 1.25,
          letterSpacingPx: 0.8,
          textTransform: "uppercase",
          textDecoration: "none",
          color: "#ffffff",
          backgroundColor: "#0055ff",
          borderRadiusPx: 999,
          borderWidthPx: 0,
          heightPx: 48,
          paddingXpx: 24,
          paddingYpx: 12,
          sourceSelector: "button.primary",
          confidence: "high",
        },
        buttonSecondary: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 16,
          fontWeight: 500,
          lineHeightPx: 20,
          lineHeightRatio: 1.25,
          letterSpacingPx: 0,
          textTransform: "none",
          textDecoration: "none",
          color: "#0055ff",
          backgroundColor: "#ffffff",
          borderRadiusPx: 999,
          borderWidthPx: 1,
          heightPx: 48,
          paddingXpx: 24,
          paddingYpx: 12,
          sourceSelector: "button.secondary",
          confidence: "medium",
        },
        input: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 16,
          fontWeight: 400,
          lineHeightPx: 24,
          lineHeightRatio: 1.5,
          letterSpacingPx: 0,
          textTransform: "none",
          textDecoration: "none",
          color: "#111111",
          backgroundColor: "#ffffff",
          borderRadiusPx: 16,
          borderWidthPx: 1,
          heightPx: 52,
          paddingXpx: 18,
          paddingYpx: 12,
          sourceSelector: "input",
          confidence: "high",
        },
        cardTitle: {
          fontStack: "Sora, sans-serif",
          primaryFamily: "Sora",
          fontSizePx: 24,
          fontWeight: 600,
          lineHeightPx: 30,
          lineHeightRatio: 1.25,
          letterSpacingPx: 0,
          textTransform: "none",
          textDecoration: "none",
          color: "#111111",
          backgroundColor: null,
          borderRadiusPx: 4,
          borderWidthPx: 0,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: ".card h3",
          confidence: "medium",
        },
        cardBody: {
          fontStack: "Inter, sans-serif",
          primaryFamily: "Inter",
          fontSizePx: 16,
          fontWeight: 400,
          lineHeightPx: 27,
          lineHeightRatio: 1.7,
          letterSpacingPx: 0,
          textTransform: "none",
          textDecoration: "none",
          color: "#555555",
          backgroundColor: null,
          borderRadiusPx: null,
          borderWidthPx: null,
          heightPx: null,
          paddingXpx: null,
          paddingYpx: null,
          sourceSelector: ".card p",
          confidence: "medium",
        },
      },
      componentStyleVariants: {
        buttonPrimary: [
          {
            fontStack: "Inter, sans-serif",
            primaryFamily: "Inter",
            fontSizePx: 16,
            fontWeight: 600,
            lineHeightPx: 20,
            lineHeightRatio: 1.25,
            letterSpacingPx: 0.8,
            textTransform: "uppercase",
            textDecoration: "none",
            color: "#ffffff",
            backgroundColor: "#0055ff",
            borderRadiusPx: 999,
            borderWidthPx: 0,
            heightPx: 48,
            paddingXpx: 24,
            paddingYpx: 12,
            sourceSelector: "button.primary",
            confidence: "high",
          },
          {
            fontStack: "Inter, sans-serif",
            primaryFamily: "Inter",
            fontSizePx: 15,
            fontWeight: 500,
            lineHeightPx: 18,
            lineHeightRatio: 1.2,
            letterSpacingPx: 0,
            textTransform: "none",
            textDecoration: "none",
            color: "#111111",
            backgroundColor: "#f3f4f6",
            borderRadiusPx: 12,
            borderWidthPx: 1,
            heightPx: 42,
            paddingXpx: 18,
            paddingYpx: 10,
            sourceSelector: "button.primary.alt",
            confidence: "medium",
          },
        ],
        cardTitle: [
          {
            fontStack: "Sora, sans-serif",
            primaryFamily: "Sora",
            fontSizePx: 24,
            fontWeight: 600,
            lineHeightPx: 30,
            lineHeightRatio: 1.25,
            letterSpacingPx: 0,
            textTransform: "none",
            textDecoration: "none",
            color: "#111111",
            backgroundColor: null,
            borderRadiusPx: 4,
            borderWidthPx: 0,
            heightPx: null,
            paddingXpx: null,
            paddingYpx: null,
            sourceSelector: ".card h3",
            confidence: "medium",
          },
          {
            fontStack: "Sora, sans-serif",
            primaryFamily: "Sora",
            fontSizePx: 20,
            fontWeight: 600,
            lineHeightPx: 26,
            lineHeightRatio: 1.3,
            letterSpacingPx: 0,
            textTransform: "uppercase",
            textDecoration: "none",
            color: "#333333",
            backgroundColor: null,
            borderRadiusPx: 8,
            borderWidthPx: 0,
            heightPx: null,
            paddingXpx: null,
            paddingYpx: null,
            sourceSelector: ".issue-card h3",
            confidence: "medium",
          },
        ],
      },
    });

    expect(prompt).toContain("TEXT ROLE REFERENCES");
    expect(prompt).toContain("- H2: size 40px, weight 700, line-height 1.15, letter-spacing -0.6px, transform uppercase, text #181818");
    expect(prompt).toContain("- Links: size 16px, weight 500, line-height 1.50, decoration underline, text #0055ff");
    expect(prompt).toContain("- Nav links: size 14px, weight 600, line-height 1.43, letter-spacing 1.2px, transform uppercase, text #222222");
    expect(prompt).toContain("COMPONENT ROLE REFERENCES");
    expect(prompt).toContain("- Primary button: size 16px, weight 600, line-height 1.25, letter-spacing 0.8px, transform uppercase, text #ffffff, fill #0055ff, radius 999px, height 48px, padding-x 24px, padding-y 12px");
    expect(prompt).toContain("- Primary button variant 2: size 15px, weight 500, line-height 1.20, text #111111, fill #f3f4f6, radius 12px, border 1px, height 42px, padding-x 18px, padding-y 10px");
    expect(prompt).toContain("- Secondary button: size 16px, weight 500, line-height 1.25, text #0055ff, fill #ffffff, radius 999px, border 1px, height 48px, padding-x 24px, padding-y 12px");
    expect(prompt).toContain("- Input: size 16px, weight 400, line-height 1.50, text #111111, fill #ffffff, radius 16px, border 1px, height 52px, padding-x 18px, padding-y 12px");
    expect(prompt).toContain("- Card title: size 24px, weight 600, line-height 1.25, text #111111, radius 4px");
    expect(prompt).toContain("- Card title variant 2: size 20px, weight 600, line-height 1.30, transform uppercase, text #333333, radius 8px");
    expect(prompt).toContain("- Card body: size 16px, weight 400, line-height 1.70, text #555555");
    expect(prompt).toContain("- Card radius: 28px");
  });

  test("falls back to legacy metrics when component styles are unavailable", () => {
    const prompt = buildPrompt({
      title: "Fallback",
      finalUrl: "https://fallback.test",
      palette: [],
      fonts: {
        display: "Fraunces",
        body: "System UI",
        mono: "SF Mono",
        headingSize: "48px",
        bodySize: "17px",
        lineHeight: "1.60",
      },
      tags: [],
      layout: {
        structure: "Stacked sections",
        width: "1024px",
        spacing: "Moderate",
        density: "Balanced",
        gap: "20px",
        sectionPadding: "80px",
      },
      sections: [],
      radius: { label: "Subtle rounded controls", average: 12 },
      shadow: "Mostly flat surfaces",
      header: { label: "Minimal header", height: "72px", navLinks: 3, hasCta: false },
      footer: { label: "Simple footer", columns: "2 columns" },
      borders: { width: "No visible borders", cardRadius: "18px", cardShadow: "No card shadows" },
      buttonDetails: { height: "44px", style: "Outlined" },
      description: "",
    });

    expect(prompt).toContain("- Heading size: 48px");
    expect(prompt).toContain("- Body size: 17px");
    expect(prompt).toContain("- Line height: 1.60");
    expect(prompt).toContain("- Palette: Not detected");
    expect(prompt).toContain("- Detected: No clear section pattern detected");
    expect(prompt).not.toContain("TEXT ROLE REFERENCES");
    expect(prompt).not.toContain("COMPONENT ROLE REFERENCES");
  });
});
